#!/bin/sh
for arg in $*
do
   echo $arg
   echo $#
done

# relink existing casks to the new location
for f in ~/Applications/*.app;
do
	oldloc="$(readlink "$f")"; [[ -e $oldloc ]] || ln -sf "/usr/local${oldloc#/opt/homebrew-cask}" "$f";
done
