#!/bin/bash
output=names.out
filename=names.in
while IFS='' read -r line || [[ -n "$line" ]]; do
    shuffled=$(echo $line | gsed 's/./&\n/g' | gshuf | tr -d "\n")
    echo $shuffled >> $output
done < "$filename"

line="Fakhrul Islam"
shuffled=$(echo $line | gsed 's/./&\n/g' | gshuf | tr -d "\n")

sed 's/./&\n/g'




# split file contants by SPACE
cat bgtxtall.txt | sed "s/ /\n/g" | sort > tmp.txt

sort bgtxtall.txt | uniq > tmp.txt
