master-data:
  bank-accounts:
  - 14131050002359
  - 14111060000068
  modes:
  - Cash
  - Cheque
  - Bank
  months:
  - Dec21.
  - Jan22.
  - Feb22.
  - Mar22.
  - Apr22.
  - May22.
  - Jun22.
selection:
  selected-account: '14111060000068'
  selected-mode: Cheque
  selected-month: Dec21.
  selected-reference: 22/001
